#!/usr/bin/env bash
# Install and configure HAProxy load balancer

sudo apt-get -y upgrade
sudo apt-get -y update
sudo apt-get install -y haproxy

sudo sed -i "8 a\ENABLED=1\n" /etc/default/haproxy

sudo sed -i "$ a\ \nfrontend load_balancer\n\tbind\t0.0.0.0:80\n\tmode\thttp\n\tdefault_backend\tweb_servers\n\nbackend web_servers\n\tbalance\troundrobin\n\tserver\t1531-web-01\t34.148.9.175:80\n\tserver\t1531-web-02\t3.239.86.235:80" /etc/haproxy/haproxy.cfg

sudo service haproxy start
