#!/usr/bin/env bash
# Removes every process using port 80 and starts nginx
kill -9 "$(lsof -t -i:80)"
sudo sed -i 's/8080 default_server/80 default_server/g' /etc/nginx/sites-enabled/default
service nginx restart
