#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes.
for i in {1..100}; do
  if ! ((i % 3)) && ! ((i % 5)); then
    echo "FizzBuzz"
  elif ! ((i % 3)); then
    echo "Fizz"
  elif ! ((i % 5)); then
    echo "Buzz"
  else
    echo "$i"
  fi
done
