#!/usr/bin/env bash
# Displays Best School 10 times using while loop.
i=1
while [ $i -lt 10 ]; do
  if [ $i -eq 9 ]; then
    printf 'Best School\nHi\n'
  fi
  printf 'Best School\n'
  (( i++ ))
done
