#!/usr/bin/env bash
# Displays Best School 10 times using while loop.
i=1
while [ $i -le 10 ]; do
  if [ $i -eq 4 ]; then
    echo "bad luck"
  elif [ $i -eq 8 ]; then
    echo "good luck"
  else
    printf 'Best School\n'
  fi
  (( i++ ))
done
