#!/usr/bin/env bash
# Displays Best School 10 times using while loop.
i=1
while [ $i -le 20 ]; do
  case $i in
    4) echo "bad luck from China";;
    9) echo "bad luck from Japan";;
    17) echo "bad luck from Italy";;
    *) echo "$i";;
  esac
  (( i++ ))
done
